spring:
  application.name: configuration-manager-ui

server:
  port: 8080
  compression.enabled:  true
  jetty:
# By default Jetty does not have a max-thread setting, we will apply this change in the configuration file.
    max-threads:  200

---
spring:
  profiles: test
  data:
    mongodb:
      host: localhost
      database: test

---
spring:
  profiles: production
  data.mongodb:
    host: localhost
    port: 27017
